<div id="content-heading">

Delete This Event
</div>
<br>
<p>Are you sure that you want to delete the event 
  '<?php echo $this->escape($this->event['name']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div class="buttonn">
  <input type="hidden" name="id" value="<?php echo $this->event['id']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
</p>
